stages:
  octagones:
    cmd: python src/prepare_polygons.py

  brush-work:
    cmd: python src/prepare_masks.py

  multiplication:
    cmd: python src/data_augmentation.py

  k2000:
    cmd: python src/deeplabv3_plus.py --type dl
    params:
    - k2000.epochs
    metrics:
    - k2000.json:
        cache: false
        persist: true
    outs:
    - k2000/mIoU_density.jpg:
        cache: false
        persist: true
    - k2000/Dice_coefficient_density.jpg:
        cache: false
        persist: true
    - k2000/inference.jpg:
        cache: false
        persist: true
    plots:
    - k2000/mIoU.csv:
        cache: false
        persist: true
        title: mIoU k2000
        x: pics
        y: mIoU
    - k2000/Dice_coefficient.csv:
        cache: false
        persist: true
        title: Dice Coefficient k2000
        x: pics
        y: Dice_coefficient
    - k2000/accuracy_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Accuracy k2000
        template: multi_loss
        x: epoch
        y: accuracy
    - k2000/loss_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Loss k2000
        template: multi_loss
        x: epoch
        y: loss

  dolorean:
    cmd: python src/U-Net_Xception.py --type dl
    metrics:
    - dolorean.json:
        cache: false
        persist: true
    outs:
    - dolorean/mIoU_density.jpg:
        cache: false
        persist: true
    - dolorean/Dice_coefficient_density.jpg:
        cache: false
        persist: true
    - dolorean/inference.jpg:
        cache: false
        persist: true
    plots:
    - dolorean/mIoU.csv:
        cache: false
        persist: true
        title: mIoU dolorean
        x: pics
        y: mIoU
    - dolorean/Dice_coefficient.csv:
        cache: false
        persist: true
        title: Dice Coefficient dolorean
        x: pics
        y: Dice_coefficient
    - dolorean/accuracy_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Accuracy dolorean
        template: multi_loss
        x: epoch
        y: accuracy
    - dolorean/loss_multi_plots.csv:
        cache: false
        persist: true
        title: Train/Test Loss dolorean
        template: multi_loss
        x: epoch
        y: loss

  comparison:
    cmd: python src/compare.py --type dl
    plots:
      - comparison/accuracy_multi_plots.csv:
          cache: false
          persist: true
          title: Train/Test Accuracy dolorean
          template: multi_loss
          x: epoch
          y: accuracy
      - comparison/loss_multi_plots.csv:
          cache: false
          persist: true
          title: Train/Test Loss dolorean
          template: multi_loss
          x: epoch
          y: loss
