stages:
  octagones:
    cmd: python src/prepare_polygons.py
  brush-work:
    cmd: python src/prepare_masks.py
  k2000:
    cmd: python src/deeplabv3_plus.py
    params:
      - k2000.epochs
    metrics:
      - k2000.json:
          cache: false
          persist: true
      - dvclive/mIoU.tsv:
          cache: false
          persist: true
    outs:
      - models/k2000:
          cache: false
          persist: true
          desc: modeling of the segmentation of images of Cityscapes.
    plots:
      - k2000/accuracy_multi_plots.csv:
          cache: false
          persist: true
          title: Train/Test Accuracy k2000
          template: multi_loss
          x: epoch
          y: accuracy
      - k2000/loss_multi_plots.csv:
          cache: false
          persist: true
          title: Train/Test Loss k2000
          template: multi_loss
          x: epoch
          y: loss

  kit:
    cmd: python src/inference.py