stages:
  octagones:
    cmd: python src/prepare_polygons.py
  brush-work:
    cmd: python src/prepare_masks.py
  k2000:
    cmd: python src/deeplabv3_plus.py
    outs:
      - models/k2000:
          cache: false
          persist: false
          desc: modelisation of the segmentation of images of Cityscapes.
  kit:
    cmd: python src/inference.py