constants:
  wce_beta: 0.7
  bce_beta: 0.5

k2000:
  epochs: 20
  data_mix: multiplication
  name: k2000
  test_size: 500
  optim_type: adam
  learning_rate: 0.001

dolorean:
  epochs: 20
  data_mix: multiplication
  name: dolorean
  test_size: 500
  optim_type: adam
  learning_rate: 0.001
