constants:
  wce_beta: 0.7
  bce_beta: 0.5

k2000:
  epochs: 3
  data_mix: original_version
  name: k2000
  test_size: 100
  optim_type: adam
  learning_rate: 0.001

dolorean:
  epochs: 3
  data_mix: original_version
  name: dolorean
  test_size: 100
  optim_type: adam
  learning_rate: 0.001
